lock liquidity on position view
invariant-labs/webapp-eclipse pull request #186
Opened 2024-11-21 16:49 UTC by matepal00

2024-11-21 18:32 UTC, wojciech-cichocki requested changes
This inversion button does not work:
![image](https://github.com/user-attachments/assets/76c9ad0d-785c-4a38-aab2-e1bc85e7f23d)

2024-11-21 18:33 UTC, wojciech-cichocki requested changes
Add hover to the fee (similar to other places):
![image](https://github.com/user-attachments/assets/37eb066b-61f7-4fc3-9903-77cae72e5e11)

2024-11-22 10:43 UTC, p6te commented
you can add tooltip on hover on lock button in position details, similar to other buttons 
![image](https://github.com/user-attachments/assets/31301757-9c04-4a07-97ee-a108949f707d)

2024-11-22 10:47 UTC, p6te commented
![image](https://github.com/user-attachments/assets/2579e51a-48d5-493a-b728-d687509b9c23)

modal on mobile view should be displayed from the top of window

2024-11-22 10:48 UTC, p6te commented
i can't scroll modal to the very bottom on mobile view 
![image](https://github.com/user-attachments/assets/5fd0259e-0a86-4627-890f-db276351a2aa)

2024-11-22 10:55 UTC, p6te commented
please change the direction of items to column for mobile view. something like that 
![image](https://github.com/user-attachments/assets/bbdb004b-0968-4b6b-acba-31c4752f8b01)

2024-11-22 13:08 UTC, p6te commented
![image](https://github.com/user-attachments/assets/36674506-0661-4db7-9cae-1a4f488d0c32)

the close button overlays the modal title on mobile

2024-11-28 23:39 UTC, wojciech-cichocki requested changes
Here's how it currently looks. The button styling doesn't look good:
![image](https://github.com/user-attachments/assets/b6a8ac98-cc4e-4110-a0b6-f794a7363e71)

According to current design lock should be located it is located on the right side
![image](https://github.com/user-attachments/assets/6971eca8-ee2c-4cef-83b9-2378fe323a11)

2024-11-29 02:37 UTC, wojciech-cichocki requested changes
Here is the text for the locker:

[TITLE]
Lock Position

[DESCRIPTION]
**Are you sure you want to lock your liquidity permanently?** Once locked, you will no longer be able to withdraw tokens from this position. Locking liquidity is often used for specific purposes, such as protecting against rug pulls.

Before locking, double-check the parameters of your position (e.g., price range and fee tier). These settings cannot be changed once the position is locked. If you need to adjust the parameters, you can close and reopen the position with the correct settings before locking.

The Invariant locker allows the wallet that locks the position to claim any fees accumulated from swaps.

[WARNING TEXT]
Once locked, the position cannot be closed, and the tokens cannot be withdrawn. Please ensure you fully understand the consequences before proceeding.

[BUTTON]
Lock Position

2024-11-29 19:39 UTC, Sniezka1927 commented
![image](https://github.com/user-attachments/assets/aa441658-6724-4808-8885-67950dcfda84)
Lock button should be disabled on locked position details

2024-12-03 12:19 UTC, Sniezka1927 requested changes

2024-12-03 12:19 UTC, Sniezka1927 commented on src/utils/utils.ts
> +      .filter(pool => pool.fee)
I think it is not needed anymore

2024-12-03 12:19 UTC, Sniezka1927 commented on src/components/PositionDetails/PositionDetails.tsx
> +  const { success, inProgress } = useSelector(lockerState)
It should be getted in container and passed to component through props

2024-12-03 12:19 UTC, Sniezka1927 commented on src/components/PositionsList/PositionsList.tsx
> +    _: React.MouseEvent<HTMLElement>,
You can't ignore arugment with `_` in typescript. If you don't need it you might want to don't pass it at all

2024-12-03 12:19 UTC, Sniezka1927 commented on src/containers/WrappedStats/WrappedStats.tsx
> +      console.log(poolData)
leftovers

2024-12-03 12:19 UTC, Sniezka1927 commented on src/store/sagas/positions.ts
> +    const { lockedList, lockedAddresses } = yield* all({
It will be better to wrap whole lockedList logic in try catch above, When the `getPostionList` fails it means user does not have any locked positions. 99% of users will never lock any position so we can reduce the number of queries to RPC

2024-12-03 12:19 UTC, Sniezka1927 commented on src/store/sagas/positions.ts
> +    if (lockedPositions.length > 0) {
Is this check needed?

2024-12-03 15:10 UTC, matepal00 commented on src/components/PositionsList/PositionsList.tsx
> +    _: React.MouseEvent<HTMLElement>,
actually this is default return from this toggle component i am using from mui, and currently i dont have unused cariable warning there so it works as ignored argument right?

2024-12-03 21:38 UTC, Sniezka1927 approved these changes

2024-12-03 22:28 UTC, merged