Add concentration as query param
invariant-labs/webapp-eclipse pull request #292
Opened 2024-12-24 09:08 UTC by kuba80-02

2024-12-27 05:45 UTC, wojciech-cichocki requested changes
Changes to the concentration level in the UI do not update the URL. It currently works only one way—changes to the URL update the UI. It should work both ways

2024-12-30 06:02 UTC, wojciech-cichocki requested changes
Use `40x` as default concentration

2024-12-30 06:14 UTC, wojciech-cichocki requested changes
I believe we can take advantage of the fact that the concentration level is stored in the URL when switching from "concentration" to "range" mode. This stored level can then be used to restore the previous concentration level when switching back from "range" mode to "concentration." Currently, the concentration level is reset to 2x by default

[Screencast from 30.12.2024 07:02:39.webm](https://github.com/user-attachments/assets/b3bc4ea4-bcef-48bb-8f99-7775d9fb542a)

2024-12-30 09:10 UTC, p6te commented
[Nagranie ekranu z 30.12.2024 10:08:32.webm](https://github.com/user-attachments/assets/ec282ecd-6657-4aef-ab03-063854306957)
when you open pair without pool, the concentration is not shown in URL

2024-12-30 09:11 UTC, p6te commented
[Nagranie ekranu z 30.12.2024 10:07:47.webm](https://github.com/user-attachments/assets/f6923fb1-2611-4485-87a4-63fe1c8fe8b3)
on new pool view, concentration is not updated in URL, when it is changed

2024-12-30 09:19 UTC, p6te commented
[Nagranie ekranu z 30.12.2024 10:17:31.webm](https://github.com/user-attachments/assets/22569355-ec8c-4379-af9b-4a01f251ca7a)
when i redirect to add position from pool links, the concentration is often set to max possible. should it be set to 40x?

2025-01-30 10:18 UTC, closed without merging