DRAFT: token creator fn v2
invariant-labs/webapp-eclipse pull request #70
Opened 2024-10-16 11:05 UTC by matepal00

2024-10-23 13:21 UTC, p6te commented on src/store/consts/static.ts
> +  console.log(network)
leftover

2024-10-23 13:27 UTC, p6te commented on src/store/consts/static.ts
> +export const TESTNET_WETH_CREATE_TOKEN_LAMPORTS = new BN(1100000)
it should be 0.011 for testnet and 0.002 for mainnet? i think is missing one zero

2024-10-24 09:11 UTC, wojciech-cichocki requested changes
Change order of nav:
exchange - liquidity - creator - statistics

2024-10-24 15:02 UTC, wojciech-cichocki approved these changes

2024-10-24 15:02 UTC, merged